### ISSUE TITLE
郁闷，加上EOEN模版代码就报错

### ISSUE THREAD

**Issue by Brania** [eoen/WeCenter-EOEN-Template#3]
![image](https://cloud.githubusercontent.com/assets/25029047/25128282/bd745118-246b-11e7-85e5-b44fc9601196.png)

部署步骤：将模版文件覆盖到Wecenter代码中

**Comment by eoen** [comment]
我明天看几时写一个安装教程

**Comment by Brania** [comment]
楼主您好，按照教程http://wecenter.eoen.org/?/article/4我操作了一边，只要将模版的文件覆盖进去直接报错500

**Comment by eoen** [comment]
是不是全新的wecente系统？有没有修改过任何文件？web环境是什么系统？
